### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Ghosst42** [webburza/sylius-article-bundle#13]
Hi!

I cannot install this package with Sylius 0.18. Any ETA on an update?
- don't install sylius/core v0.17.0|don't install sylius/sylius v0.18.0
- don't install sylius/core v0.17.0|remove sylius/sylius v0.18.0
- don't install sylius/core v0.17.0|don't install sylius/sylius v0.18.0
- webburza/sylius-article-bundle 0.2.2 requires sylius/core ^0.17 -> satisfiable by sylius/core[v0.17.0].
- Installation request for webburza/sylius-article-bundle ^0.2.2 -> satisfiable by webburza/sylius-article-bundle[0.2.2].
- Installation request for sylius/sylius ^0.18@dev -> satisfiable by sylius/sylius[v0.18.0].

Thank you!

**Comment by ychanan** [comment]
Hello,

we've started updating our bundles and should have this one ready for Sylius 0.18 within a week. We'll keep you posted. :)

**Comment by ychanan** [comment]
We've just released version v0.3.0 for Sylius 0.18.
We'd really appreciate any feedback you can provide. :)

**Comment by Ghosst42** [comment]
Thank you! That was really fast. I will check it tonight!
