### ISSUE TITLE
extend article

### ISSUE THREAD

**Issue by kajpol** [webburza/sylius-article-bundle#15]
Hi

I'd like to extend an Article entity so i'll be able to implement taggable extension.
Is it currently possible? If no, is it possible to implement such functionality in your bundle?

Thanks.

**Comment by ychanan** [comment]
Sure, you can extend the Article entity with whatever you like. The class is not referenced anywhere, instead we use interfaces so any class implementing the same interface should work.

Check the config.yml file and override the model property to point to your class, which in turn would extend our Article class. In the next interation we'll simplify this process to use parameters, but it should work even now.

**Comment by kajpol** [comment]
Thanks for fast reply.
What i meant to say is that without [@ORM\MappedSuperclass()](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#overrides)  annotation proper extending of entity, with reuse of same table, is not possible. 

As for configuration i think that it's clear enough  - it's standard sylius implementation of ResourceInterface.
I appreciate all of your bundles , really nice way to find out different aspects of extending sylius.

**Comment by ychanan** [comment]
Hi Kajpol, sorry for the wait. The bundle has now been upgraded for Sylius 1.0@beta release, and mapping now uses mapped super-classes instead of entities, and is done via XML.
