### ISSUE TITLE
upgrade to 0.19 - 1.0

### ISSUE THREAD

**Issue by antonioperic** [webburza/sylius-article-bundle#17]
any plans for this?

**Comment by ivangrgur** [comment]
Hi @antonioperic ,

As the version 1.0 just got out we can’t commit to any deadline right now. But, we’re surely going to share our plan about the update of all our bundles to version 1.0. through August.

**Comment by ychanan** [comment]
Hi Antonio. 

We'll upgrade all our bundles to Sylius 0.19 throughout the next couple of weeks, and from that point on keep up with Sylius (development version) releases on a more regular basis.
